#############################################################################
# Makefile for building: bin/adb-sync
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  adb-sync.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile adb-sync.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/.moc -Ibuild/.ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = adb-sync1.0.0
DISTDIR = /mnt/data/Igrek/c++/adb-sync/build/.obj/adb-sync1.0.0
LINK          = g++
LFLAGS        = -m64 -lboost_system -lboost_thread -g -rdynamic -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/lib/x86_64-linux-gnu -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/.obj/

####### Files

SOURCES       = src/main.cpp \
		src/logger/Logger.cpp \
		src/dispatcher/EventDispatcher.cpp \
		src/dispatcher/IEventObserver.cpp \
		src/dispatcher/Event.cpp \
		src/dispatcher/EventClass.cpp \
		src/config/ConfigLoader.cpp \
		src/config/ConfigProperties.cpp \
		src/config/Database.cpp \
		src/errors/Error.cpp \
		src/filesystem/FileSystem.cpp \
		src/filesystem/LocalFS.cpp \
		src/filesystem/ADB.cpp \
		src/filesystem/File.cpp \
		src/filesystem/Directory.cpp \
		src/filesystem/RegularFile.cpp \
		src/gui/GUI.cpp \
		src/gui/MainWindow.cpp \
		src/gui/DiffListBox.cpp \
		src/synchronizer/Synchronizer.cpp \
		src/system/CommandExecutor.cpp \
		src/synchronizer/DiffScanner.cpp \
		src/diffs/Diff.cpp \
		src/threads/SingleThread.cpp \
		src/threads/Thread.cpp \
		src/threads/LoopThread.cpp \
		src/App.cpp \
		src/utils/string_utils.cpp \
		src/errors/SystemCmdError.cpp \
		src/errors/ParseError.cpp \
		src/test/TestApp.cpp \
		src/synchronizer/DiffSync.cpp build/.moc/moc_MainWindow.cpp
OBJECTS       = build/.obj/main.o \
		build/.obj/Logger.o \
		build/.obj/EventDispatcher.o \
		build/.obj/IEventObserver.o \
		build/.obj/Event.o \
		build/.obj/EventClass.o \
		build/.obj/ConfigLoader.o \
		build/.obj/ConfigProperties.o \
		build/.obj/Database.o \
		build/.obj/Error.o \
		build/.obj/FileSystem.o \
		build/.obj/LocalFS.o \
		build/.obj/ADB.o \
		build/.obj/File.o \
		build/.obj/Directory.o \
		build/.obj/RegularFile.o \
		build/.obj/GUI.o \
		build/.obj/MainWindow.o \
		build/.obj/DiffListBox.o \
		build/.obj/Synchronizer.o \
		build/.obj/CommandExecutor.o \
		build/.obj/DiffScanner.o \
		build/.obj/Diff.o \
		build/.obj/SingleThread.o \
		build/.obj/Thread.o \
		build/.obj/LoopThread.o \
		build/.obj/App.o \
		build/.obj/string_utils.o \
		build/.obj/SystemCmdError.o \
		build/.obj/ParseError.o \
		build/.obj/TestApp.o \
		build/.obj/DiffSync.o \
		build/.obj/moc_MainWindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		adb-sync.pro src/logger/Logger.h \
		src/dispatcher/EventDispatcher.h \
		src/dispatcher/IEventObserver.h \
		src/dispatcher/Event.h \
		src/dispatcher/EventClass.h \
		src/config/ConfigLoader.h \
		src/config/ConfigProperties.h \
		src/config/Database.h \
		src/errors/Error.h \
		src/filesystem/FileSystem.h \
		src/filesystem/LocalFS.h \
		src/filesystem/ADB.h \
		src/filesystem/File.h \
		src/filesystem/Directory.h \
		src/filesystem/RegularFile.h \
		src/gui/GUI.h \
		src/gui/MainWindow.h \
		src/gui/DiffListBox.h \
		src/synchronizer/Synchronizer.h \
		src/system/CommandExecutor.h \
		src/synchronizer/DiffScanner.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h \
		src/threads/SingleThread.h \
		src/threads/Thread.h \
		src/threads/LoopThread.h \
		src/App.h \
		src/utils/string_utils.h \
		src/errors/SystemCmdError.h \
		src/errors/ParseError.h \
		src/events/DiffInvertedButtonClicked.h \
		src/events/DiffListUpdateRequest.h \
		src/events/DiffRemovedButtonClicked.h \
		src/events/DiffScanButtonClicked.h \
		src/events/DiffPartialScanCompleted.h \
		src/events/DiffSyncCompleted.h \
		src/events/ExecuteAllDiffsButtonClicked.h \
		src/events/ExecuteDiffButtonClicked.h \
		src/events/ProgressUpdated.h \
		src/events/ShowUIMessageRequest.h \
		src/synchronizer/DiffSync.h \
		src/test/TestApp.h \
		src/test/LocalFSTest.h \
		src/test/QApplicationTest.h \
		src/test/ThreadsTest.h \
		src/test/BusyboxTest.h src/main.cpp \
		src/logger/Logger.cpp \
		src/dispatcher/EventDispatcher.cpp \
		src/dispatcher/IEventObserver.cpp \
		src/dispatcher/Event.cpp \
		src/dispatcher/EventClass.cpp \
		src/config/ConfigLoader.cpp \
		src/config/ConfigProperties.cpp \
		src/config/Database.cpp \
		src/errors/Error.cpp \
		src/filesystem/FileSystem.cpp \
		src/filesystem/LocalFS.cpp \
		src/filesystem/ADB.cpp \
		src/filesystem/File.cpp \
		src/filesystem/Directory.cpp \
		src/filesystem/RegularFile.cpp \
		src/gui/GUI.cpp \
		src/gui/MainWindow.cpp \
		src/gui/DiffListBox.cpp \
		src/synchronizer/Synchronizer.cpp \
		src/system/CommandExecutor.cpp \
		src/synchronizer/DiffScanner.cpp \
		src/diffs/Diff.cpp \
		src/threads/SingleThread.cpp \
		src/threads/Thread.cpp \
		src/threads/LoopThread.cpp \
		src/App.cpp \
		src/utils/string_utils.cpp \
		src/errors/SystemCmdError.cpp \
		src/errors/ParseError.cpp \
		src/test/TestApp.cpp \
		src/synchronizer/DiffSync.cpp
QMAKE_TARGET  = adb-sync
DESTDIR       = bin/
TARGET        = bin/adb-sync


first: all
####### Build rules

$(TARGET): build/.ui/ui_mainwindow.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: adb-sync.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		adb-sync.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile adb-sync.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
adb-sync.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile adb-sync.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/logger/Logger.h src/dispatcher/EventDispatcher.h src/dispatcher/IEventObserver.h src/dispatcher/Event.h src/dispatcher/EventClass.h src/config/ConfigLoader.h src/config/ConfigProperties.h src/config/Database.h src/errors/Error.h src/filesystem/FileSystem.h src/filesystem/LocalFS.h src/filesystem/ADB.h src/filesystem/File.h src/filesystem/Directory.h src/filesystem/RegularFile.h src/gui/GUI.h src/gui/MainWindow.h src/gui/DiffListBox.h src/synchronizer/Synchronizer.h src/system/CommandExecutor.h src/synchronizer/DiffScanner.h src/diffs/Diff.h src/diffs/DiffType.h src/threads/SingleThread.h src/threads/Thread.h src/threads/LoopThread.h src/App.h src/utils/string_utils.h src/errors/SystemCmdError.h src/errors/ParseError.h src/events/DiffInvertedButtonClicked.h src/events/DiffListUpdateRequest.h src/events/DiffRemovedButtonClicked.h src/events/DiffScanButtonClicked.h src/events/DiffPartialScanCompleted.h src/events/DiffSyncCompleted.h src/events/ExecuteAllDiffsButtonClicked.h src/events/ExecuteDiffButtonClicked.h src/events/ProgressUpdated.h src/events/ShowUIMessageRequest.h src/synchronizer/DiffSync.h src/test/TestApp.h src/test/LocalFSTest.h src/test/QApplicationTest.h src/test/ThreadsTest.h src/test/BusyboxTest.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/logger/Logger.cpp src/dispatcher/EventDispatcher.cpp src/dispatcher/IEventObserver.cpp src/dispatcher/Event.cpp src/dispatcher/EventClass.cpp src/config/ConfigLoader.cpp src/config/ConfigProperties.cpp src/config/Database.cpp src/errors/Error.cpp src/filesystem/FileSystem.cpp src/filesystem/LocalFS.cpp src/filesystem/ADB.cpp src/filesystem/File.cpp src/filesystem/Directory.cpp src/filesystem/RegularFile.cpp src/gui/GUI.cpp src/gui/MainWindow.cpp src/gui/DiffListBox.cpp src/synchronizer/Synchronizer.cpp src/system/CommandExecutor.cpp src/synchronizer/DiffScanner.cpp src/diffs/Diff.cpp src/threads/SingleThread.cpp src/threads/Thread.cpp src/threads/LoopThread.cpp src/App.cpp src/utils/string_utils.cpp src/errors/SystemCmdError.cpp src/errors/ParseError.cpp src/test/TestApp.cpp src/synchronizer/DiffSync.cpp $(DISTDIR)/
	$(COPY_FILE) --parents forms/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: build/.moc/moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/.moc/moc_MainWindow.cpp
build/.moc/moc_MainWindow.cpp: src/gui/DiffListBox.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h \
		src/gui/MainWindow.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/mnt/data/Igrek/c++/adb-sync -I/mnt/data/Igrek/c++/adb-sync -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6.3.1 -I/usr/include/c++/6.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include-fixed -I/usr/include src/gui/MainWindow.h -o build/.moc/moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/.ui/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) build/.ui/ui_mainwindow.h
build/.ui/ui_mainwindow.h: forms/mainwindow.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic forms/mainwindow.ui -o build/.ui/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/.obj/main.o: src/main.cpp src/App.h \
		src/synchronizer/Synchronizer.h \
		src/config/Database.h \
		src/dispatcher/IEventObserver.h \
		src/dispatcher/Event.h \
		src/synchronizer/DiffScanner.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h \
		src/filesystem/LocalFS.h \
		src/filesystem/FileSystem.h \
		src/filesystem/File.h \
		src/filesystem/RegularFile.h \
		src/filesystem/Directory.h \
		src/filesystem/ADB.h \
		src/threads/SingleThread.h \
		src/synchronizer/DiffSync.h \
		src/config/ConfigLoader.h \
		src/config/ConfigProperties.h \
		src/gui/GUI.h \
		src/gui/MainWindow.h \
		src/gui/DiffListBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/main.o src/main.cpp

build/.obj/Logger.o: src/logger/Logger.cpp src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/Logger.o src/logger/Logger.cpp

build/.obj/EventDispatcher.o: src/dispatcher/EventDispatcher.cpp src/dispatcher/EventDispatcher.h \
		src/dispatcher/IEventObserver.h \
		src/dispatcher/Event.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h \
		src/dispatcher/EventClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/EventDispatcher.o src/dispatcher/EventDispatcher.cpp

build/.obj/IEventObserver.o: src/dispatcher/IEventObserver.cpp src/dispatcher/IEventObserver.h \
		src/dispatcher/Event.h \
		src/dispatcher/EventDispatcher.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h \
		src/dispatcher/EventClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/IEventObserver.o src/dispatcher/IEventObserver.cpp

build/.obj/Event.o: src/dispatcher/Event.cpp src/dispatcher/Event.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/Event.o src/dispatcher/Event.cpp

build/.obj/EventClass.o: src/dispatcher/EventClass.cpp src/dispatcher/EventClass.h \
		src/dispatcher/Event.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/EventClass.o src/dispatcher/EventClass.cpp

build/.obj/ConfigLoader.o: src/config/ConfigLoader.cpp src/config/ConfigLoader.h \
		src/config/ConfigProperties.h \
		src/config/Database.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h \
		src/utils/string_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/ConfigLoader.o src/config/ConfigLoader.cpp

build/.obj/ConfigProperties.o: src/config/ConfigProperties.cpp src/config/ConfigProperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/ConfigProperties.o src/config/ConfigProperties.cpp

build/.obj/Database.o: src/config/Database.cpp src/config/Database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/Database.o src/config/Database.cpp

build/.obj/Error.o: src/errors/Error.cpp src/errors/Error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/Error.o src/errors/Error.cpp

build/.obj/FileSystem.o: src/filesystem/FileSystem.cpp src/filesystem/FileSystem.h \
		src/filesystem/File.h \
		src/filesystem/RegularFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/FileSystem.o src/filesystem/FileSystem.cpp

build/.obj/LocalFS.o: src/filesystem/LocalFS.cpp src/filesystem/LocalFS.h \
		src/filesystem/FileSystem.h \
		src/filesystem/File.h \
		src/filesystem/RegularFile.h \
		src/filesystem/Directory.h \
		src/errors/ParseError.h \
		src/errors/Error.h \
		src/utils/string_utils.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/system/CommandExecutor.h \
		src/errors/SystemCmdError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/LocalFS.o src/filesystem/LocalFS.cpp

build/.obj/ADB.o: src/filesystem/ADB.cpp src/filesystem/ADB.h \
		src/filesystem/FileSystem.h \
		src/filesystem/File.h \
		src/filesystem/RegularFile.h \
		src/filesystem/Directory.h \
		src/errors/Error.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/system/CommandExecutor.h \
		src/errors/SystemCmdError.h \
		src/utils/string_utils.h \
		src/errors/ParseError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/ADB.o src/filesystem/ADB.cpp

build/.obj/File.o: src/filesystem/File.cpp src/filesystem/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/File.o src/filesystem/File.cpp

build/.obj/Directory.o: src/filesystem/Directory.cpp src/filesystem/Directory.h \
		src/filesystem/File.h \
		src/filesystem/RegularFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/Directory.o src/filesystem/Directory.cpp

build/.obj/RegularFile.o: src/filesystem/RegularFile.cpp src/filesystem/RegularFile.h \
		src/filesystem/File.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/RegularFile.o src/filesystem/RegularFile.cpp

build/.obj/GUI.o: src/gui/GUI.cpp src/gui/GUI.h \
		src/gui/MainWindow.h \
		src/gui/DiffListBox.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h \
		src/dispatcher/IEventObserver.h \
		src/dispatcher/Event.h \
		src/events/ProgressUpdated.h \
		src/dispatcher/EventDispatcher.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h \
		src/dispatcher/EventClass.h \
		src/events/ShowUIMessageRequest.h \
		src/events/DiffPartialScanCompleted.h \
		src/events/DiffListUpdateRequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/GUI.o src/gui/GUI.cpp

build/.obj/MainWindow.o: src/gui/MainWindow.cpp src/gui/MainWindow.h \
		src/gui/DiffListBox.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h \
		build/.ui/ui_mainwindow.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h \
		src/events/DiffScanButtonClicked.h \
		src/dispatcher/Event.h \
		src/dispatcher/EventDispatcher.h \
		src/dispatcher/IEventObserver.h \
		src/dispatcher/EventClass.h \
		src/events/DiffRemovedButtonClicked.h \
		src/events/ExecuteDiffButtonClicked.h \
		src/events/ExecuteAllDiffsButtonClicked.h \
		src/version.h \
		src/events/DiffInvertedButtonClicked.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/MainWindow.o src/gui/MainWindow.cpp

build/.obj/DiffListBox.o: src/gui/DiffListBox.cpp src/gui/DiffListBox.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/DiffListBox.o src/gui/DiffListBox.cpp

build/.obj/Synchronizer.o: src/synchronizer/Synchronizer.cpp src/synchronizer/Synchronizer.h \
		src/config/Database.h \
		src/dispatcher/IEventObserver.h \
		src/dispatcher/Event.h \
		src/synchronizer/DiffScanner.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h \
		src/filesystem/LocalFS.h \
		src/filesystem/FileSystem.h \
		src/filesystem/File.h \
		src/filesystem/RegularFile.h \
		src/filesystem/Directory.h \
		src/filesystem/ADB.h \
		src/threads/SingleThread.h \
		src/synchronizer/DiffSync.h \
		src/config/ConfigLoader.h \
		src/config/ConfigProperties.h \
		src/dispatcher/EventDispatcher.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h \
		src/dispatcher/EventClass.h \
		src/events/DiffScanButtonClicked.h \
		src/events/DiffRemovedButtonClicked.h \
		src/events/ShowUIMessageRequest.h \
		src/events/DiffListUpdateRequest.h \
		src/events/ExecuteDiffButtonClicked.h \
		src/events/ExecuteAllDiffsButtonClicked.h \
		src/events/DiffInvertedButtonClicked.h \
		src/events/DiffPartialScanCompleted.h \
		src/events/DiffSyncCompleted.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/Synchronizer.o src/synchronizer/Synchronizer.cpp

build/.obj/CommandExecutor.o: src/system/CommandExecutor.cpp src/system/CommandExecutor.h \
		src/errors/SystemCmdError.h \
		src/errors/Error.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/CommandExecutor.o src/system/CommandExecutor.cpp

build/.obj/DiffScanner.o: src/synchronizer/DiffScanner.cpp src/synchronizer/DiffScanner.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h \
		src/config/Database.h \
		src/filesystem/LocalFS.h \
		src/filesystem/FileSystem.h \
		src/filesystem/File.h \
		src/filesystem/RegularFile.h \
		src/filesystem/Directory.h \
		src/filesystem/ADB.h \
		src/threads/SingleThread.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h \
		src/dispatcher/EventDispatcher.h \
		src/dispatcher/IEventObserver.h \
		src/dispatcher/Event.h \
		src/dispatcher/EventClass.h \
		src/events/ProgressUpdated.h \
		src/events/ShowUIMessageRequest.h \
		src/events/DiffPartialScanCompleted.h \
		src/events/DiffListUpdateRequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/DiffScanner.o src/synchronizer/DiffScanner.cpp

build/.obj/Diff.o: src/diffs/Diff.cpp src/diffs/Diff.h \
		src/diffs/DiffType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/Diff.o src/diffs/Diff.cpp

build/.obj/SingleThread.o: src/threads/SingleThread.cpp src/threads/SingleThread.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/SingleThread.o src/threads/SingleThread.cpp

build/.obj/Thread.o: src/threads/Thread.cpp src/threads/Thread.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/Thread.o src/threads/Thread.cpp

build/.obj/LoopThread.o: src/threads/LoopThread.cpp src/threads/LoopThread.h \
		src/threads/SingleThread.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/LoopThread.o src/threads/LoopThread.cpp

build/.obj/App.o: src/App.cpp src/App.h \
		src/synchronizer/Synchronizer.h \
		src/config/Database.h \
		src/dispatcher/IEventObserver.h \
		src/dispatcher/Event.h \
		src/synchronizer/DiffScanner.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h \
		src/filesystem/LocalFS.h \
		src/filesystem/FileSystem.h \
		src/filesystem/File.h \
		src/filesystem/RegularFile.h \
		src/filesystem/Directory.h \
		src/filesystem/ADB.h \
		src/threads/SingleThread.h \
		src/synchronizer/DiffSync.h \
		src/config/ConfigLoader.h \
		src/config/ConfigProperties.h \
		src/gui/GUI.h \
		src/gui/MainWindow.h \
		src/gui/DiffListBox.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/App.o src/App.cpp

build/.obj/string_utils.o: src/utils/string_utils.cpp src/utils/string_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/string_utils.o src/utils/string_utils.cpp

build/.obj/SystemCmdError.o: src/errors/SystemCmdError.cpp src/errors/SystemCmdError.h \
		src/errors/Error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/SystemCmdError.o src/errors/SystemCmdError.cpp

build/.obj/ParseError.o: src/errors/ParseError.cpp src/errors/ParseError.h \
		src/errors/Error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/ParseError.o src/errors/ParseError.cpp

build/.obj/TestApp.o: src/test/TestApp.cpp src/test/TestApp.h \
		src/App.h \
		src/synchronizer/Synchronizer.h \
		src/config/Database.h \
		src/dispatcher/IEventObserver.h \
		src/dispatcher/Event.h \
		src/synchronizer/DiffScanner.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h \
		src/filesystem/LocalFS.h \
		src/filesystem/FileSystem.h \
		src/filesystem/File.h \
		src/filesystem/RegularFile.h \
		src/filesystem/Directory.h \
		src/filesystem/ADB.h \
		src/threads/SingleThread.h \
		src/synchronizer/DiffSync.h \
		src/config/ConfigLoader.h \
		src/config/ConfigProperties.h \
		src/gui/GUI.h \
		src/gui/MainWindow.h \
		src/gui/DiffListBox.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/TestApp.o src/test/TestApp.cpp

build/.obj/DiffSync.o: src/synchronizer/DiffSync.cpp src/synchronizer/DiffSync.h \
		src/diffs/Diff.h \
		src/diffs/DiffType.h \
		src/filesystem/ADB.h \
		src/filesystem/FileSystem.h \
		src/filesystem/File.h \
		src/filesystem/RegularFile.h \
		src/filesystem/Directory.h \
		src/filesystem/LocalFS.h \
		src/threads/SingleThread.h \
		src/dispatcher/EventDispatcher.h \
		src/dispatcher/IEventObserver.h \
		src/dispatcher/Event.h \
		src/logger/Logger.h \
		src/logger/LogLevel.h \
		src/errors/Error.h \
		src/dispatcher/EventClass.h \
		src/events/ProgressUpdated.h \
		src/events/DiffSyncCompleted.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/DiffSync.o src/synchronizer/DiffSync.cpp

build/.obj/moc_MainWindow.o: build/.moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/.obj/moc_MainWindow.o build/.moc/moc_MainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

